### ISSUE TITLE
in dynamic styles with value combing

### ISSUE THREAD

**Issue by paxarpp** [lttb/reshadow#23]
in dynamic styles with value combing, 1 class is created, it was expected that when calculating the value, a separate class will be created for each value.
```
const isFirst = ({ active }) =>
  active === 0 &&
  css`
    transform: translateX(0);
  `;

const isTwo = ({ active }) =>
  active === 1 &&
  css`
    transform: translateX(-${({ width }) => width}px);
  `;

const isThree = ({ active }) =>
  active === 2 &&
  css`
    transform: translateX(-${({ width }) => 2 * width}px);
  `;

const isFour = ({ active }) =>
  active === 3 &&
  css`
    transform: translateX(-${({ width }) => 3 * width}px);
  `;

const Wrapper = styled.div`
  height: 400px;
  width: ${({ width }) => 4 * width}px;
  display: flex;
  flex-flow: row nowrap;
  transition: all 1s cubic-bezier(0.4, 1.21, 1, 0.99);
  ${isFirst};
  ${isTwo};
  ${isThree};
  ${isFour};
`;
```
![combing](https://user-images.githubusercontent.com/34523588/58764683-08fc5a80-8573-11e9-8775-74484da9d09c.JPG)

**Comment by lttb** [comment]
Hi @paxarpp, thank you again for the issue!

This is an expected behaviour, and this is why reshadow has such efficient runtime.

The idea is that we can generate just one class, for example, but achieve the dynamic by the `css-custom-propterties`, that will be changed during the runtime.

This way, `isTwo` will set styles like:
```css
transform: translateX(var(--32cknz_1));
```

And instead of updating the stylesheet on each render with new values, all we need to do - just set the custom css property "--32cknz_1"

Unfortunately, this expression would not work in CSS:
```css
transform: translateX(-var(--32cknz_1)px);
```

because CSS engine will not concatenate strings '-', value of variable and 'px' out of the box.

There are a few workarounds:
1) use function `calc`:
    ```js
    css`
        transform: translateX(calc(${() => width} * 1px));
    `
    ```
2) I made a fix for reshadow to support smarter units interpolation, so this code will also work (starting from `alpha.53`):
    ```js
    css`
        transform: translateX(${() => -width}px);
    `
    ```

    So here I just moved the `minus` to the dynamic value.

    Theoretically, it is also possible to support `minus` in dynamic values too, but I'm not sure that it worths it. But I'll think about it too.

So there is a working example with smarter units:
https://codesandbox.io/s/reshadowstyled-y58gc

**Comment by paxarpp** [comment]
thanks for the detailed and quick reply
