### ISSUE TITLE
How to use babel-plugin-import

### ISSUE THREAD

**Issue by comerc** [lttb/reshadow#41]
Please support this [plugin](https://www.npmjs.com/package/babel-plugin-import).

**Comment by antonk52** [comment]
Hi. Thank you for the issue. Can you please expand on what you mean by supporting this plugin?

I can see see that it is intended to be used with modular utility/component based libraries. From my experience it looks pretty similar to [`babel-plugin-transform-imports`](https://www.npmjs.com/package/babel-plugin-transform-imports) but you also get to tune it to import `css` or other assets too.

Since reshadow is neither a utility nor component library I am not sure how exactly we can support this plugin. If I misunderstood your intend please feel free to correct me.

**Comment by comerc** [comment]
I use common lib [reshadow](https://www.npmjs.com/package/reshadow). (Instead of [@reshadow/macro](https://www.npmjs.com/package/@reshadow/macro) for example.

i.e.
`import styled, { css } from 'reshadow/macro'`
instead of 
`import styled, { css } from '@reshadow/macro'`

And I assumed then I have all unused code of reshadow in my bundle. But experiment with CRA denied it. Sorry.
